### PR TITLE
Add default config for ogc-api-records microservice

### PR DESCRIPTION
**Pull request by jahow**
Inspired by the work done on Géo2france.

### CODE REVIEW

**Comment by landryb** [comment]
is there documentation somewhere about how to build & deploy such microservice ? i suppose it's like gn-cloud-searching for rss ... but more context would be welcome :)

**Comment by jahow** [comment]
Yes indeed, this is lacking context, sorry. The [ogc-api-records microservice](https://github.com/geonetwork/geonetwork-microservices/tree/main/modules/services/ogc-api-records) provides (as the name suggests) an OGC API endpoint.

For docker users there is [an open issue](https://github.com/georchestra/docker/issues/145) to add this service in the default composition. For ansible I could not find anything.

I guess this PR doesn't make much sense if the service is not part of the default deployment...

**Comment by landryb** [comment]
> Yes indeed, this is lacking context, sorry. The [ogc-api-records microservice](https://github.com/geonetwork/geonetwork-microservices/tree/main/modules/services/ogc-api-records) provides (as the name suggests) an OGC API Records endpoint which gives another search API on top of GeoNetwork 4.x.

Right, thanks for that :) we already have a buildjob building the searching service on https://packages.georchestra.org, maybe we should add ogc-api-records to it ?

> For docker users there is [an open issue](https://github.com/georchestra/docker/issues/145) to add this service in the default composition. For ansible I could not find anything.

well, for searching microservice @pmauduit did georchestra/ansible#90 so it shouldnt be that hard to do something similar.. is there an expected default url the service should be available on ? `/geonetwork/collections` or something ? with some specific headers, as was the case for the searching microservice ?

> I guess this PR doesn't make much sense if the service is not part of the default deployment...

it makes totally sense if this is meant to be part of the default deployment :)

**Comment by jahow** [comment]
I'm going to stall a bit on that one. I'm not sure yet which approach should be taken for the ogc-api microservice, I'll gather opinions around me first.

**Comment by fvanderbiest** [comment]
I'm +1 on integrating the ogc-api-records microservice to the geOrchestra deployment process by default.
In the end, we'll have more and more microservices.

**Comment by fvanderbiest** [comment]
> Right, thanks for that :) we already have a buildjob building the searching service on https://packages.georchestra.org, maybe we should add ogc-api-records to it ?

Yes.

> it makes totally sense if this is meant to be part of the default deployment :)

That's our ambition indeed !

Merging, since it is a first step which does not harm anything.

**Comment by landryb** [comment]
Fwiw, testing it and i'm a bit confused. This PR adds `config.yml` to the datadir, and so far my tries at running it standalone:
```
/etc/georchestra/geonetwork/microservices/ogc-api-records $env SPRING_PROFILES_ACTIVE=standalone SPRING_CONFIG_LOCATION=./ JAVA_OPTS=-Dfile.encoding=UTF-8 java -jar /usr/share/lib/gn-ogc-api-records.jar
```
badly fail, from my understanding the config file isnt read since it tries to fetch one over http.
```
2023-03-29 16:01:27.504  INFO 3287037 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Fetching config from server at : http://localhost:8888
2023-03-29 16:01:27.658  INFO 3287037 --- [           main] c.c.c.ConfigServicePropertySourceLocator : Connect Timeout Exception on Url - http://localhost:8888. Will be trying the next url if available
```

After tinkering/comparing with the rss service, renaming the config file to `application.yml` makes it start fine.

for the rss microservice, the config is named `gn-cloud-searching-application.yml`. What should be the right correct name for this microservice config file ?

**Comment by jahow** [comment]
I think your best bet is to take inspiration from the docker composition (which is not merged yet):
https://github.com/georchestra/docker/pull/172/files#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3

You can use the `SPRING_CONFIG_LOCATION` env var to point explicitly on the config file.

**Comment by landryb** [comment]
> I think your best bet is to take inspiration from the docker composition (which is not merged yet): https://github.com/georchestra/docker/pull/172/files#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3

yeah that's more or less what i was already trying :)

> You can use the `SPRING_CONFIG_LOCATION` env var to point explicitly on the config file.

sure, that works with
```
env SERVER_SERVLET_CONTEXT_PATH=/ogc-api-records SPRING_PROFILES_ACTIVE=standalone SPRING_CONFIG_LOCATION=./config.yml JAVA_OPTS=-Dfile.encoding=UTF-8 SERVER_PORT=8480 java -jar /usr/share/lib/gn-ogc-api-records.jar
```
but what confused me is that for the rss microservice, pointing at the config file wasnt needed, it found the yml in https://github.com/georchestra/datadir/tree/master/geonetwork/microservices/searching by only giving it a directory in the systemd unit in https://github.com/georchestra/ansible/blob/master/roles/georchestra/templates/geonetwork/gn-cloud-searching.service.j2#L8

now it works, with some proxying behind apache:
```
$cat /var/www/georchestra/conf/ogc-api-records.conf
<Proxy http://localhost:8480/ogc-api-records/*>
    Require all granted
</Proxy>

ProxyPass /ogc-api-records/ http://localhost:8480/ogc-api-records/
ProxyPassReverse /ogc-api-records/ http://localhost:8480/ogc-api-records/
```
*but* some bits arent properly working, because i still have links with http://localhost:8480/ogc-api-records/ in the source code of the pages, the relative links dont have the FQDN ?
```
<p class="uppercase tracking-loose w-full"><a href="[http://localhost:8480/ogc-api-records/collections](view-source:http://localhost:8480/ogc-api-records/collections)">Browse collections&nbsp;</a></p>
```
clicking on the `/openapi/` link redirects to http://localhost:8480/openapi/swagger-ui/ which cant work. I guess i'm missing a setting somewhere that tells the microservice what's the full URI it's supposed to be at, but after testing i cant use a full url in SERVER_SERVLET_CONTEXT_PATH. Maybe in docker land this is handled by traefik or the gateway, but should there be some Host env variable passing in apache ?

since links are broken i cant browse but going manually to collections and items sortof works, with some errors related to the index keywords here and there.. so more debugging needed.
```
2023-03-29 16:29:38.139 ERROR 3288284 --- [nio-8480-exec-2] org.fao.geonet.ogcapi.records            : An error occurred while building JSON-LD representation of record 'f9f1560b-a788-4d86-9c9c-74479cbe692d'. Error is: Unrecognized field "name" (class org.fao.geonet.index.model.gn.Link), not marked as ignorable (8 known properties: "protocol", "applicationProfile", "nameObject", "descriptionObject", "mimeType", "group", "function", "urlObject"])
```

**Comment by landryb** [comment]
after digging more about the `Unrecognized field "name"` error message, i think it's linked to the georchestra fork of geonetwork not having bits of geonetwork/core-geonetwork#6588 & geonetwork/geonetwork-microservices#68 - so there's a tight adherence between the versions of the microservice and the geonetwork.

I *think* i finally have everything working against geonetwork 4.2.2 (eg no more gross errors in the logs, `?f=dcat` export working) when the microservice is built from https://github.com/geonetwork/geonetwork-microservices/releases/tag/4.2.2.

the only broken bit is the openapi link but i see it's broken too on https://dev.geo2france.fr/ogc-api-records/ (eg redirects to https://dev.geo2france.fr/openapi/swagger-ui/ which is a 404)  - i've tried fiddling with the baseUrl/paths in https://github.com/georchestra/datadir/blob/master/geonetwork/microservices/ogc-api-records/config.yml#L124 adding `/ogc-api-records/` as a prefix, but it only triggers 404s.

**Pull request merged**
