### PR TITLE
Trying to put a custom dialect / schema for GN

### PR DESCRIPTION
**Pull request by pmauduit**
Runtime tests: into a docker composition, following the workflow described below:

- [x] only geonetwork, and related containers
- [x] relaunching previous composition
- [x] a more complete composition
- [x] relaunching previous composition

### CODE REVIEW

**Comment by pmauduit** [comment]
Also tested in a regular `mvn jetty:run` setup, it is working correctly.

**Comment by fvanderbiest** [comment]
LGTM, please merge

**Comment by pmauduit** [comment]
It should also be ported back to master after merge.

**Comment by pmauduit** [comment]
Done with https://github.com/georchestra/datadir/commit/e68753793ecb1725affb399246343845f8bfa906

**Pull request merged**
