### PR TITLE
Mapstore: Add more plugins to mobile mode

### PR DESCRIPTION
**Pull request by tkohr**
The PR adds the following plugins to the "burger" menu:
- "Share"
- "MetadataExplorer" => allows adding layers in mobile mode (which surprisingly does not seem possible for now)
- ~~"Measure" => the angle measuring seems to have a bug on mobile, we should perhaps not add it for now~~
- "MapImport"
- "MapExport"

and button at the bottom right:
- "GlobeViewSwitcher" => allows switching to 3D

Only tested in devtools so far, not on real phone.

### CODE REVIEW

**Comment by fvanderbiest** [comment]
Yep, "measure" does not seem like a good addition on mobile.

**Comment by tkohr** [comment]
Ok, I got rid of it :-)

**Comment by fvanderbiest** [comment]
ported to master and docker branches

**Comment by landryb** [comment]
Nice ! Fwiw i had filed a similar report upstream for cesium mode, cf geosolutions-it/MapStore2#8057.

you might also want to commit your changes to https://github.com/georchestra/mapstore2-georchestra/blob/master/configs/localConfig.json so that files are kept in sync.... which might be a lost cause anyway.

**Comment by fvanderbiest** [comment]
> you might also want to commit your changes to https://github.com/georchestra/mapstore2-georchestra/blob/master/configs/localConfig.json so that files are kept in sync.... which might be a lost cause anyway.

Tried to homogeneize using meld, but I'm not confident enough...

**Pull request merged**
