### PR TITLE
datafeeder: upgrade connection params to use the `postgis` container

### PR DESCRIPTION
**Pull request by groldan**
The default docker composition shall define a docker container called
`postgis` to use as the target for ingesting datafeeder uploaded
datasets.

This changes the config in order to use the default georchestra
PostgreSQL database to store application import process metadata, but a
separate PostGIS database and container to import the uploaded datasets
into, hence separating concerns, given that datafeeder will create
several database schemas.

See https://github.com/georchestra/docker/issues/100

### CODE REVIEW

**Comment by jeanpommier** [comment]
Hi @groldan 
Shouldn't you target docker-master branch ?

**Comment by fvanderbiest** [comment]
> Shouldn't you target docker-master branch ?

Right !
LGTM otherwise

**Comment by jeanpommier** [comment]
> LGTM otherwise

Yep, to me too

**Comment by groldan** [comment]
by looking at other commits I though the process was to target master and then merge to docker-master

**Comment by fvanderbiest** [comment]
> by looking at other commits I though the process was to target master and then merge to docker-master

You're right Gabriel. 
For changes which impact the docker and non-docker cases, we target master first, then merge to docker-master.
Here the change only impacts the docker case => there's no need to change anything in the master branch

**Pull request merged**
