### PR TITLE
mapstore - remove cookie warning

### PR DESCRIPTION
**Pull request by fvanderbiest**
See https://github.com/georchestra/georchestra/issues/3821

### CODE REVIEW

**Comment by landryb** [comment]
well.. technically, mapstore uses a cookie, no ? IANAL but GDPR etc... sure, it's annoying, but ... no ?

**Comment by fvanderbiest** [comment]
Well, if the cookie is required for the service, there is no requirement for a warning message. See eg https://www.cnil.fr/fr/cookies-et-autres-traceurs/regles/cookies/que-dit-la-loi

**Review by landryb — APPROVED** [review]
fine with me then, i'm not smart enough for all this mumbojumbo anyway :)

**Comment by fvanderbiest** [comment]
Ported to docker-master with [17efe5b](https://github.com/georchestra/datadir/pull/294/commits/17efe5bcf63bc6e05f944d08cd5c2bfdb2ba1cb0)

**Pull request merged**
