### PR TITLE
Use dedicated UserAgent for extractor app

### PR DESCRIPTION
**Pull request by Vampouille**

### CODE REVIEW

**Comment by pmauduit** [comment]
Looks good :)

**Comment by pmauduit** [comment]
After having discussed, we propose to use another UA instead, see https://github.com/georchestra/georchestra/pull/1182#issuecomment-171999435

**Comment by Vampouille** [comment]
No change needed on datadir repo.

**Comment by fvanderbiest** [comment]
Fixed with https://github.com/georchestra/datadir/commit/16f73693e0da82293072154dab1fba77dacd2ea3

**Pull request closed without merging**
