### PR TITLE
[mapstore] update printing config

### PR DESCRIPTION
**Pull request by landryb**
mostly to merge geosolutions-it/MapStore2@4b267214d6
but also realignes with upstream config, instead of copying the one from mfapp?
- use 'fixed' scales as that's what end users constantly complain about
- use an inline data: url for brokenUrlPlaceholder
- ditch the section about basic auth, no opinion on that one
- all the other changes are whitespace fixes coming from upstream ms2

### CODE REVIEW

**Comment by landryb** [comment]
to be backported/merged/cherrypicked onto 22.0 ofc.

**Comment by fvanderbiest** [comment]
Removing basic auth means you should not be able to print protected layers again.
Is it expected ?

**Comment by fvanderbiest** [comment]
Removing basic auth means you should not be able to print protected layers again.
Is it expected ?

**Comment by landryb** [comment]
> Removing basic auth means you should not be able to print protected layers again. Is it expected ?

i dunno i never used that feature, that's why i said i had no opinion about that particular chunk. Can readd if preferred :)

**Comment by fvanderbiest** [comment]
OK, looks good to me then. 
I would not backport all the changes to 22.0 since this would change print resolutions on a stable release - we don't want that.

**Comment by landryb** [comment]
> I would not backport all the changes to 22.0 since this would change print resolutions on a stable release - we don't want that.

fwiw, in that case most of the bits should be backported anyway, otherwise users on 22.0 trying to print with svg images will fail as reported in https://github.com/geosolutions-it/MapStore2/issues/7807

**Comment by fvanderbiest** [comment]
backported to 22.0

**Pull request merged**
