### PR TITLE
align geostore.properties to commit 9ba3bac9bea7dfd6d3c899ee93aeaf6a049f058a

### PR DESCRIPTION
**Pull request by lpasquali**
Hello @fvanderbiest 

since we updated the name of the pg schema from "geostore" to "mapstore" we need also to modify this file to make mapstore awayre of the correct schema.
Also the schema name change affects two files in georchestra/mapstore2-georchestra repository:
https://github.com/georchestra/mapstore2-georchestra/tree/master/database

### CODE REVIEW

**Comment by fvanderbiest** [comment]
Yes.

Regarding the SQL files, their integration in the geOrchestra project is still pending, with https://github.com/georchestra/georchestra/pull/3058/files

**Comment by lpasquali** [comment]
> Yes.
> 
> Regarding the SQL files, their integration in the geOrchestra project is still pending, with the (ill-named) [georchestra/georchestra#3058](https://github.com/georchestra/georchestra/pull/3058)

the sigle sql file with mapstore name was merged short while ago: https://github.com/georchestra/mapstore2-georchestra/tree/master/database

**Comment by fvanderbiest** [comment]
> the sigle sql file with mapstore name was merged short while ago: https://github.com/georchestra/mapstore2-georchestra/tree/master/database

OK, but IMO it should also be added in https://github.com/georchestra/georchestra/tree/master/postgresql

**Comment by lpasquali** [comment]
conflicts resolved, this can be merged

**Pull request merged**
