### PR TITLE
security-proxy: Add timeout configuration

### PR DESCRIPTION
**Pull request by Vampouille**

### CODE REVIEW

**Comment by pmauduit** [comment]
looks good (I'd have use a more self-explainatory variable name - `http_client_timeout` -, but that is ok)

**Comment by fvanderbiest** [comment]
+1 with Pierre to rename into a more self-explainatory variable name

**Comment by landryb** [comment]
Should the apache default config be in line with this ? Or that's just internal ?

**Comment by Vampouille** [comment]
just internal, it allow long exchange between geoserver and extractor.

**Pull request merged**
