### PR TITLE
Update gateway config

### PR DESCRIPTION
**Pull request by f-necas**
Solves problem with redirections and geoserver proxyBaseUrl. 

https://github.com/georchestra/georchestra/blob/master/docs/setup/tomcat.md#in-case-of-troubles-with-the-geoserver-ui

See :
- https://github.com/georchestra/helm-georchestra/pull/60
- https://github.com/georchestra/georchestra/blob/master/docs/setup/tomcat.md#in-case-of-troubles-with-the-geoserver-ui
- https://github.com/georchestra/georchestra-gateway/pull/104

### CODE REVIEW

**Comment by landryb** [comment]
oh, will check if that helps the issue i was seeing when testing in https://github.com/georchestra/ansible/issues/128#issuecomment-2012642332

**Comment by landryb** [comment]
while here, should something be done about the `geowebcache` route ? it's not completely defined in the `master` branch thus gateway fails to start:
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'spring.cloud.gateway.routes[6].uri' to java.net.URI:

    Property: spring.cloud.gateway.routes[6].uri
    Value: "${georchestra.gateway.services.geowebcache.target}"
    Origin: URL [file:/etc/georchestra/gateway/routes.yaml] - 41:14
    Reason: failed to convert java.lang.String to @javax.validation.constraints.NotNull java.net.URI (caused by java.lang.IllegalArgumentException: Invalid URI syntax: Illegal character in path at index 1: ${georchestra.gateway.services.geowebcache.target})

Action:

Update your application's configuration
```

**Comment by pmauduit** [comment]
> while here, should something be done about the `geowebcache` route ?

maybe add a `georchestra.gateway.services.geowebcache.target: http://localhost:8280/geowebcache/` to the master branch of the datadir, routes.yaml file here:
https://github.com/georchestra/datadir/blob/master/gateway/routes.yaml#L72

**Comment by landryb** [comment]
> > while here, should something be done about the `geowebcache` route ?
> 
> maybe add a `georchestra.gateway.services.geowebcache.target: http://localhost:8280/geowebcache/` to the master branch of the datadir, routes.yaml file here: https://github.com/georchestra/datadir/blob/master/gateway/routes.yaml#L72

also works, gateway starts fine with:
```
diff --git a/gateway/routes.yaml b/gateway/routes.yaml
index e320915..2a757ae 100644
--- a/gateway/routes.yaml
+++ b/gateway/routes.yaml
@@ -70,6 +70,7 @@ georchestra.gateway.services:
   datafeeder.target: http://localhost:8480/datafeeder/
   datahub.target: http://localhost:8280/datahub/
   geonetwork.target: http://localhost:8280/geonetwork/
+  geowebcache.target: http://localhost:8280/geowebcache/
   geoserver.target: http://localhost:8380/geoserver/
   header.target: http://localhost:8280/header/
   import.target: http://localhost:8280/import/
```

**Comment by pmauduit** [comment]
> sorry :D

grmbl :smiling_imp:

**Comment by landryb** [comment]
gwc startup fixed with [2b01654](https://github.com/georchestra/datadir/pull/397/commits/2b01654a4d7c7c49ecdba8709d178713b015a3ff) - afaict for me this is ok to merge.

**Review by landryb — APPROVED** [review]
can't comment on the yaml magic but it works !

**Pull request merged**
