### PR TITLE
[datafeeder] align with georchestra/ansible@3731520

### PR DESCRIPTION
**Pull request by landryb**
fix thesaurus name ? to be backported onto 22.0 ?

### CODE REVIEW

**Comment by fvanderbiest** [comment]
LGTM, cc @pmauduit ?

**Review by pmauduit — APPROVED** [review]
ok, but it will require to "revert" https://github.com/georchestra/ansible/commit/3731520098ee26c1763fc14ed8cbc79f39799887#diff-2238294e9898c1e661f3076fb24f9fe3564896283c83fab7a339a5fb8efb541cR26 ?

**Comment by fvanderbiest** [comment]
uh ?

**Comment by pmauduit** [comment]
> uh ?

if the modification is made into the datadir, then there is no need to "override" the value from the playbook

**Comment by fvanderbiest** [comment]
got it !

**Comment by fvanderbiest** [comment]
backported to 22.0

**Pull request merged**
