### PR TITLE
extractor - add configuration to store extraction logs

### PR DESCRIPTION
**Pull request by Vampouille**

### CODE REVIEW

**Comment by Vampouille** [comment]
This is configuration for : https://github.com/georchestra/georchestra/pull/1566

**Comment by fvanderbiest** [comment]
LGTM.
Maybe one comment line stating that it targets the `extractorapp` schema ?

**Comment by Vampouille** [comment]
> Maybe one comment line stating that it targets the extractorapp schema ?

Done by amending last commit

**Comment by fvanderbiest** [comment]
OKay, please merge

**Pull request merged**
