### PR TITLE
Update ms2 config files for mapstore 2021.02.00

### PR DESCRIPTION
**Pull request by landryb**
cf georchestra/mapstore2-georchestra#428, georchestra/mapstore2-georchestra#410 & https://mapstore2.readthedocs.io/en/latest/developer-guide/mapstore-migration-guide/#migration-from-20210102-to-20210200

### CODE REVIEW

**Comment by landryb** [comment]
@offtherailz i was unsure that `pluginsConfig.json` was necessary since it wasnt initially added in #182, but in my pov it's better to have samples for all 'overridable' files, no ? or it will quickly get out of sync with the one in the war, and ppl arent supposed to modify it much ?

**Comment by landryb** [comment]
cf georchestra/mapstore2-georchestra#422 too.

**Comment by offtherailz** [comment]
@landryb about the samples and the update, you get the point. We avoid to include these files in data dir because updates are hard. So we suggest to keep only customizations and overrides in the data-dir.

**Comment by landryb** [comment]
If `pluginsConfig.json` isnt edited much, then yes it makes sense to not have it in the datadir. that would have just been for discoverability..

**Review by pmauduit — APPROVED** [review]

**Pull request merged**
